version: "3.2"
services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "mydb"

  mysso:
    build:
      context: .
      args:
        GITHUB_USERNAME: "gr3gdev"
        GITHUB_TOKEN: "35171f251b989ba4b0bb6b61a1bcb6597dd5119e"
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_URL: "jdbc:postgresql://db:5432/mydb"
    depends_on:
      - db
    ports:
      - 3000:3000