CREATE TABLE IF NOT EXISTS users (
    USERNAME TEXT PRIMARY KEY,
    PASSWORD TEXT NOT NULL,
    ENABLED BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
    CLIENT_NAME TEXT PRIMARY KEY,
    CLIENT_SECRET TEXT NOT NULL,
    REMOTE_ADDRESSES TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS authorities (
    USERNAME TEXT,
    CLIENT_NAME TEXT,
    ROLE TEXT,
    PRIMARY KEY (USERNAME, CLIENT_NAME),
    CONSTRAINT FK_AUTH_USERS FOREIGN KEY (USERNAME) REFERENCES users (USERNAME),
    CONSTRAINT FK_AUTH_CLIENTS FOREIGN KEY (CLIENT_NAME) REFERENCES clients (CLIENT_NAME)
);

CREATE TABLE IF NOT EXISTS users_token (
    USERNAME TEXT PRIMARY KEY,
    TOKEN TEXT NOT NULL,
    EXPIRE_DATE TIMESTAMP NOT NULL,
    CONSTRAINT FK_TOKEN_USERS FOREIGN KEY (USERNAME) REFERENCES users (USERNAME)
);
